name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6.0.0
      with:
        go-version: 1.14
    - uses: actions/checkout@v5.0.0
    - name: Test
      run: go test -v -cover .